module.exports = [
    [require('./unicorn-poison.json'), 3],
    [require('./back-kick.json'), 3],
    [require('./change-of-luck.json'), 2],
    [require('./glitter-tornado.json'), 2],
    [require('./unicorn-swap.json'), 2],
    [require('./re-target.json'), 2],
    [require('./unfair-bargain.json'), 2],
    [require('./two-for-one.json'), 2],
    [require('./targeted-destruction.json'), 1],
    [require('./mystical-vortex.json'), 1],
    [require('./good-deal.json'), 1],
    [require('./shake-up.json'), 1],
    [require('./blatant-thievery.json'), 1],
    [require('./reset-button.json'), 1],
    [require('./kiss-of-life.json'), 1],
];
